apiVersion: v1
kind: Service
metadata:
  name: musang-fums-app-service
  namespace: fums-dev-ns
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: musang-fums-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: musang-fums-app-config
  namespace: fums-dev-ns
data:
  NODE_ENV: "production"
  API_BASE_URL: "https://fums-api.banpuindo.co.id/api"
  ORIGIN: "https://fums.banpuindo.co.id"
  LIVE_VIEW_ACCOUNT: "asset_management@banpuindo.co.id"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musang-fums-app
  namespace: fums-dev-ns
  labels:
    app: musang-fums-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musang-fums-app
  template:
    metadata:
      labels:
        app: musang-fums-app
    spec:
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: musang-fums-app-keyvault-csi
      containers:
      - name: musang-fums-app
        image: bpitmACRdev.azurecr.io/musang-fums-app:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: musang-fums-app-config
              key: NODE_ENV
        - name: API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: musang-fums-app-config
              key: API_BASE_URL
        - name: ORIGIN
          valueFrom:
            configMapKeyRef:
              name: musang-fums-app-config
              key: ORIGIN
        - name: LIVE_VIEW_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: musang-fums-app-config
              key: LIVE_VIEW_ACCOUNT
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musang-fums-app-ingress
  namespace: fums-dev-ns
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
  - hosts:
    - fums.banpuindo.co.id
    secretName: fums-app-service-tls
  rules:
  - host: fums.banpuindo.co.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: musang-fums-app-service
            port:
              number: 80
