apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: musang-fums-app-keyvault-csi
  namespace: fums-dev-ns
spec:
  provider: azure
  secretObjects:
  - secretName: fums-app-service-tls
    type: kubernetes.io/tls
    data:
    - objectName: fums-app-service-tls
      key: tls.crt
    - objectName: fums-app-service-tls
      key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4da58ae7-d40b-4b0e-92dd-12f7145ddef8"
    keyvaultName: "itmea-test"
    objects:  |
      array:
        - |
          objectName: fums-app-service-tls
          objectType: cert
    tenantId: "bbb8da8f-f374-490f-9190-2242176e117c"
